# Generated by Django 5.1.7 on 2025-03-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('birth_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('price', models.IntegerField()),
                ('main_singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('type', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('created_date', models.DateField()),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('singers', models.ManyToManyField(to='music.singer')),
            ],
        ),
        migrations.CreateModel(
            name='SongSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_time', models.DurationField()),
                ('end_time', models.DurationField()),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.singer')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
        ),
    ]
