# Generated by Django 5.1.7 on 2025-03-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='albums',
            new_name='album',
        ),
    ]
