# Generated by Django 5.1.7 on 2025-03-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_albums_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songsinger',
            old_name='stat_time',
            new_name='start_time',
        ),
    ]
